export const ORDER_CREATE_PAYLOAD = {
  version: "0",
  id: "602a0f61-3b84-8aca-1032-61dfe80a0870",
  "detail-type": "shopifyWebhook",
  source: "aws.partner/shopify.com/201184116737/Giftclub_prod-Giftclub",
  account: "442426894654",
  time: "2025-01-31T10:31:31Z",
  region: "ap-south-1",
  resources: [],
  detail: {
    payload: {
      id: 6146108195057,
      admin_graphql_api_id: "gid://shopify/Order/6146108195057",
      app_id: 212419117057,
      browser_ip: "2401:4900:1c68:1eb0:d026:cc4e:e27b:7651",
      buyer_accepts_marketing: true,
      cancel_reason: null,
      cancelled_at: null,
      cart_token:
        "Z2NwLWFzaWEtc291dGhlYXN0MTowMUpKWFlLUlFQRDlDREVaSlc5SldURzlLTQ",
      checkout_id: 36354034696433,
      checkout_token: "4c6aa5750d833e62e261c30f87200552",
      client_details: {
        accept_language: "en-IN",
        browser_height: null,
        browser_ip: "2401:4900:1c68:1eb0:d026:cc4e:e27b:7651",
        browser_width: null,
        session_hash: null,
        user_agent:
          "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1",
      },
      closed_at: null,
      confirmation_number: "CQ3JZ8N6E",
      confirmed: true,
      contact_email: "lakshya@giftkart.ai",
      created_at: "2025-01-31T16:01:27+05:30",
      currency: "INR",
      current_shipping_price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      current_subtotal_price: "3049.00",
      current_subtotal_price_set: {
        shop_money: {
          amount: "3049.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "3049.00",
          currency_code: "INR",
        },
      },
      current_total_additional_fees_set: null,
      current_total_discounts: "0.00",
      current_total_discounts_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      current_total_duties_set: null,
      current_total_price: "3049.00",
      current_total_price_set: {
        shop_money: {
          amount: "3049.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "3049.00",
          currency_code: "INR",
        },
      },
      current_total_tax: "465.10",
      current_total_tax_set: {
        shop_money: {
          amount: "465.10",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "465.10",
          currency_code: "INR",
        },
      },
      customer_locale: "en-IN",
      device_id: null,
      discount_codes: [],
      duties_included: false,
      email: "lakshya@giftkart.ai",
      estimated_taxes: false,
      financial_status: "pending",
      fulfillment_status: null,
      landing_site: "/pages/desktop-screen",
      landing_site_ref: null,
      location_id: null,
      merchant_business_entity_id: "MTcxODAwMzI0MzM3",
      merchant_of_record_app_id: null,
      name: "#1106",
      note: null,
      note_attributes: [],
      number: 106,
      order_number: 1106,
      order_status_url:
        "https://www.giftclub.ai/71800324337/orders/91feca3e5d921d04c579a3e8f13374d8/authenticate?key=2053e726d8702c5cd13ddf3e9c9f5269",
      original_total_additional_fees_set: null,
      original_total_duties_set: null,
      payment_gateway_names: ["Cash on Delivery (COD)"],
      phone: "+919999297761",
      po_number: null,
      presentment_currency: "INR",
      processed_at: "2025-01-31T16:01:26+05:30",
      reference: null,
      referring_site:
        "https://g82qgrn7ycmfg68m-71800324337.shopifypreview.com/",
      source_identifier: null,
      source_name: "212419117057",
      source_url: null,
      subtotal_price: "3049.00",
      subtotal_price_set: {
        shop_money: {
          amount: "3049.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "3049.00",
          currency_code: "INR",
        },
      },
      tags: "",
      tax_exempt: false,
      tax_lines: [
        {
          price: "465.10",
          rate: 0.18,
          title: "IGST",
          price_set: {
            shop_money: {
              amount: "465.10",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "465.10",
              currency_code: "INR",
            },
          },
          channel_liable: false,
        },
      ],
      taxes_included: true,
      test: false,
      token: "91feca3e5d921d04c579a3e8f13374d8",
      total_cash_rounding_payment_adjustment_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_cash_rounding_refund_adjustment_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_discounts: "0.00",
      total_discounts_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_line_items_price: "3049.00",
      total_line_items_price_set: {
        shop_money: {
          amount: "3049.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "3049.00",
          currency_code: "INR",
        },
      },
      total_outstanding: "3049.00",
      total_price: "3049.00",
      total_price_set: {
        shop_money: {
          amount: "3049.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "3049.00",
          currency_code: "INR",
        },
      },
      total_shipping_price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_tax: "465.10",
      total_tax_set: {
        shop_money: {
          amount: "465.10",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "465.10",
          currency_code: "INR",
        },
      },
      total_tip_received: "0.00",
      total_weight: 0,
      updated_at: "2025-01-31T16:01:29+05:30",
      user_id: null,
      billing_address: {
        first_name: "Lakshya",
        address1: "Sector D Vasant Kunj",
        phone: null,
        city: "New Delhi",
        zip: "110070",
        province: "Delhi",
        country: "India",
        last_name: "Dev",
        address2: "appartment",
        company: null,
        latitude: null,
        longitude: null,
        name: "Lakshya Dev",
        country_code: "IN",
        province_code: "DL",
      },
      customer: {
        id: 7925853880561,
        email: "lakshya@giftkart.ai",
        created_at: "2024-12-21T16:11:48+05:30",
        updated_at: "2025-01-31T16:01:28+05:30",
        first_name: "Lakshya",
        last_name: "",
        state: "enabled",
        note: null,
        verified_email: true,
        multipass_identifier: null,
        tax_exempt: false,
        phone: "+919999297761",
        email_marketing_consent: {
          state: "subscribed",
          opt_in_level: "single_opt_in",
          consent_updated_at: "2025-01-14T00:41:40+05:30",
        },
        sms_marketing_consent: {
          state: "subscribed",
          opt_in_level: "single_opt_in",
          consent_updated_at: "2025-01-14T00:41:40+05:30",
          consent_collected_from: "OTHER",
        },
        tags: "acceptWhatsappMarketing",
        currency: "INR",
        tax_exemptions: [],
        admin_graphql_api_id: "gid://shopify/Customer/7925853880561",
        default_address: {
          id: 9355192140017,
          customer_id: 7925853880561,
          first_name: "Lakshya",
          last_name: "Dev",
          company: null,
          address1: "Sector D Vasant Kunj",
          address2: "appartment",
          city: "New Delhi",
          province: "Delhi",
          country: "India",
          zip: "110070",
          phone: null,
          name: "Lakshya Dev",
          province_code: "DL",
          country_code: "IN",
          country_name: "India",
          default: true,
        },
      },
      discount_applications: [],
      fulfillments: [],
      line_items: [
        {
          id: 14698067853553,
          admin_graphql_api_id: "gid://shopify/LineItem/14698067853553",
          attributed_staffs: [],
          current_quantity: 1,
          fulfillable_quantity: 1,
          fulfillment_service: "manual",
          fulfillment_status: null,
          gift_card: false,
          grams: 0,
          name: "Large Box",
          price: "150.00",
          price_set: {
            shop_money: {
              amount: "150.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "150.00",
              currency_code: "INR",
            },
          },
          product_exists: true,
          product_id: 8740388733169,
          properties: [],
          quantity: 1,
          requires_shipping: true,
          sku: "",
          taxable: true,
          title: "Large Box",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          variant_id: 45903263727857,
          variant_inventory_management: "shopify",
          variant_title: null,
          vendor: "giftclub",
          tax_lines: [
            {
              channel_liable: false,
              price: "22.89",
              price_set: {
                shop_money: {
                  amount: "22.89",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "22.89",
                  currency_code: "INR",
                },
              },
              rate: 0.18,
              title: "IGST",
            },
          ],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 14698067886321,
          admin_graphql_api_id: "gid://shopify/LineItem/14698067886321",
          attributed_staffs: [],
          current_quantity: 1,
          fulfillable_quantity: 1,
          fulfillment_service: "manual",
          fulfillment_status: null,
          gift_card: false,
          grams: 0,
          name: "Snitch & Vanya Bundle - M / XL",
          price: "2499.00",
          price_set: {
            shop_money: {
              amount: "2499.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "2499.00",
              currency_code: "INR",
            },
          },
          product_exists: true,
          product_id: 8740356227313,
          properties: [
            {
              name: "packaging",
              value: "true",
            },
          ],
          quantity: 1,
          requires_shipping: true,
          sku: "",
          taxable: true,
          title: "Snitch & Vanya Bundle",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          variant_id: 45903136424177,
          variant_inventory_management: null,
          variant_title: "M / XL",
          vendor: "giftclub-merchant-prod",
          tax_lines: [
            {
              channel_liable: false,
              price: "381.20",
              price_set: {
                shop_money: {
                  amount: "381.20",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "381.20",
                  currency_code: "INR",
                },
              },
              rate: 0.18,
              title: "IGST",
            },
          ],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 14698067919089,
          admin_graphql_api_id: "gid://shopify/LineItem/14698067919089",
          attributed_staffs: [],
          current_quantity: 1,
          fulfillable_quantity: 1,
          fulfillment_service: "manual",
          fulfillment_status: null,
          gift_card: false,
          grams: 0,
          name: "Medium Box",
          price: "100.00",
          price_set: {
            shop_money: {
              amount: "100.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "100.00",
              currency_code: "INR",
            },
          },
          product_exists: true,
          product_id: 8740388700401,
          properties: [],
          quantity: 1,
          requires_shipping: true,
          sku: "",
          taxable: true,
          title: "Medium Box",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          variant_id: 45903263695089,
          variant_inventory_management: "shopify",
          variant_title: null,
          vendor: "giftclub",
          tax_lines: [
            {
              channel_liable: false,
              price: "15.25",
              price_set: {
                shop_money: {
                  amount: "15.25",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "15.25",
                  currency_code: "INR",
                },
              },
              rate: 0.18,
              title: "IGST",
            },
          ],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 14698067951857,
          admin_graphql_api_id: "gid://shopify/LineItem/14698067951857",
          attributed_staffs: [],
          current_quantity: 1,
          fulfillable_quantity: 1,
          fulfillment_service: "manual",
          fulfillment_status: null,
          gift_card: false,
          grams: 0,
          name: "Give It A Whirl Earrings - Acrylic",
          price: "300.00",
          price_set: {
            shop_money: {
              amount: "300.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "300.00",
              currency_code: "INR",
            },
          },
          product_exists: true,
          product_id: 8740367073521,
          properties: [
            {
              name: "packaging",
              value: "true",
            },
          ],
          quantity: 1,
          requires_shipping: true,
          sku: null,
          taxable: true,
          title: "Give It A Whirl Earrings",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          variant_id: 45903171977457,
          variant_inventory_management: "shopify",
          variant_title: "Acrylic",
          vendor: "merchant-prod-2",
          tax_lines: [
            {
              channel_liable: false,
              price: "45.76",
              price_set: {
                shop_money: {
                  amount: "45.76",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "45.76",
                  currency_code: "INR",
                },
              },
              rate: 0.18,
              title: "IGST",
            },
          ],
          duties: [],
          discount_allocations: [],
        },
      ],
      payment_terms: null,
      refunds: [],
      shipping_address: {
        first_name: "Lakshya",
        address1: "Sector D Vasant Kunj",
        phone: null,
        city: "New Delhi",
        zip: "110070",
        province: "Delhi",
        country: "India",
        last_name: "Dev",
        address2: "appartment",
        company: null,
        latitude: 28.5254842,
        longitude: 77.1433249,
        name: "Lakshya Dev",
        country_code: "IN",
        province_code: "DL",
      },
      shipping_lines: [
        {
          id: 4964978753777,
          carrier_identifier: null,
          code: "Standard",
          current_discounted_price_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          discounted_price: "0.00",
          discounted_price_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          is_removed: false,
          phone: null,
          price: "0.00",
          price_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          requested_fulfillment_service_id: null,
          source: "shopify",
          title: "Standard",
          tax_lines: [],
          discount_allocations: [],
        },
      ],
      returns: [],
    },
    metadata: {
      "Content-Type": "application/json",
      "X-Shopify-Topic": "orders/create",
      "X-Shopify-Shop-Domain": "cygzgc-jw.myshopify.com",
      "X-Shopify-Order-Id": "6146108195057",
      "X-Shopify-Test": "false",
      "X-Shopify-Hmac-SHA256": "OtZ4Pik5O1r+5677vN6nXBiO5yp6x9dysV8lPg5W/2U=",
      "X-Shopify-Webhook-Id": "3fa07e01-4a44-40db-a990-4208f042f450",
      "X-Shopify-API-Version": "2024-10",
      "X-Shopify-Event-Id": "5679b0f5-5e63-4b5e-8756-20e16191cb34",
      "X-Shopify-Triggered-At": "2025-01-31T10:31:29.212699922Z",
    },
  },
};

export const ORDER_FULFILLED = {
  version: "0",
  id: "2bd77d80-0348-640f-ba00-6e72f773b2f9",
  "detail-type": "shopifyWebhook",
  source:
    "aws.partner/shopify.com/213761261569/Giftclub_Prod-Giftclub_Merchant_2",
  account: "442426894654",
  time: "2025-01-31T10:46:16Z",
  region: "ap-south-1",
  resources: [],
  detail: {
    payload: {
      id: 6527573459259,
      admin_graphql_api_id: "gid://shopify/Order/6527573459259",
      app_id: 213761261569,
      browser_ip: "15.207.119.171",
      buyer_accepts_marketing: false,
      cancel_reason: null,
      cancelled_at: null,
      cart_token: null,
      checkout_id: 38636727337275,
      checkout_token: "272d03928f3c0fd8e90857aebad8bfa5",
      client_details: {
        accept_language: "*",
        browser_height: null,
        browser_ip: "15.207.119.171",
        browser_width: null,
        session_hash: null,
        user_agent: "node",
      },
      closed_at: null,
      company: null,
      confirmation_number: "0G09YJUD5",
      confirmed: true,
      contact_email: "lakshya@giftkart.ai",
      created_at: "2025-01-31T05:31:40-05:00",
      currency: "INR",
      current_shipping_price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      current_subtotal_price: "400.00",
      current_subtotal_price_set: {
        shop_money: {
          amount: "400.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "400.00",
          currency_code: "INR",
        },
      },
      current_total_additional_fees_set: null,
      current_total_discounts: "0.00",
      current_total_discounts_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      current_total_duties_set: null,
      current_total_price: "400.00",
      current_total_price_set: {
        shop_money: {
          amount: "400.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "400.00",
          currency_code: "INR",
        },
      },
      current_total_tax: "61.02",
      current_total_tax_set: {
        shop_money: {
          amount: "61.02",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "61.02",
          currency_code: "INR",
        },
      },
      customer_locale: "en",
      device_id: null,
      discount_codes: [],
      duties_included: false,
      email: "lakshya@giftkart.ai",
      estimated_taxes: false,
      financial_status: "pending",
      fulfillment_status: "fulfilled",
      landing_site: null,
      landing_site_ref: null,
      location_id: null,
      merchant_business_entity_id: "MTkxOTEwNjAzMDY3",
      merchant_of_record_app_id: null,
      name: "#1018",
      note: null,
      note_attributes: [],
      number: 18,
      order_number: 1018,
      order_status_url:
        "https://merchant-prod-2.myshopify.com/91910603067/orders/db4f2b3ba290e8fea29bf55377dca726/authenticate?key=45bf1ee7bb7d7f4c3e64fd6eab01436d",
      original_total_additional_fees_set: null,
      original_total_duties_set: null,
      payment_gateway_names: ["manual"],
      phone: null,
      po_number: null,
      presentment_currency: "INR",
      processed_at: "2025-01-31T05:31:39-05:00",
      reference: null,
      referring_site: null,
      source_identifier: null,
      source_name: "213761261569",
      source_url: null,
      subtotal_price: "400.00",
      subtotal_price_set: {
        shop_money: {
          amount: "400.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "400.00",
          currency_code: "INR",
        },
      },
      tags: "generated_via_giftclub",
      tax_exempt: false,
      tax_lines: [
        {
          price: "61.02",
          rate: 0.18,
          title: "IGST",
          price_set: {
            shop_money: {
              amount: "61.02",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "61.02",
              currency_code: "INR",
            },
          },
          channel_liable: false,
        },
      ],
      taxes_included: true,
      test: false,
      token: "db4f2b3ba290e8fea29bf55377dca726",
      total_cash_rounding_payment_adjustment_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_cash_rounding_refund_adjustment_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_discounts: "0.00",
      total_discounts_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_line_items_price: "400.00",
      total_line_items_price_set: {
        shop_money: {
          amount: "400.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "400.00",
          currency_code: "INR",
        },
      },
      total_outstanding: "400.00",
      total_price: "400.00",
      total_price_set: {
        shop_money: {
          amount: "400.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "400.00",
          currency_code: "INR",
        },
      },
      total_shipping_price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_tax: "61.02",
      total_tax_set: {
        shop_money: {
          amount: "61.02",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "61.02",
          currency_code: "INR",
        },
      },
      total_tip_received: "0.00",
      total_weight: 0,
      updated_at: "2025-01-31T05:46:14-05:00",
      user_id: null,
      billing_address: null,
      customer: {
        id: 9256249819451,
        email: "lakshya@giftkart.ai",
        created_at: "2025-01-30T05:16:15-05:00",
        updated_at: "2025-01-31T05:31:40-05:00",
        first_name: null,
        last_name: "",
        state: "disabled",
        note: null,
        verified_email: true,
        multipass_identifier: null,
        tax_exempt: false,
        phone: null,
        currency: "INR",
        tax_exemptions: [],
        admin_graphql_api_id: "gid://shopify/Customer/9256249819451",
        default_address: {
          id: 10959113191739,
          customer_id: 9256249819451,
          first_name: null,
          last_name: null,
          company: null,
          address1: "Sector D Vasant Kunj",
          address2: null,
          city: "New Delhi",
          province: "Delhi",
          country: "India",
          zip: "110070",
          phone: null,
          name: "",
          province_code: "DL",
          country_code: "IN",
          country_name: "India",
          default: true,
        },
      },
      discount_applications: [],
      fulfillments: [
        {
          id: 5739340529979,
          admin_graphql_api_id: "gid://shopify/Fulfillment/5739340529979",
          created_at: "2025-01-31T05:46:14-05:00",
          location_id: 104364376379,
          name: "#1018.1",
          order_id: 6527573459259,
          origin_address: {},
          receipt: {},
          service: "manual",
          shipment_status: null,
          status: "success",
          tracking_company: null,
          tracking_number: null,
          tracking_numbers: [],
          tracking_url: null,
          tracking_urls: [],
          updated_at: "2025-01-31T05:46:14-05:00",
          line_items: [
            {
              id: 16437775106363,
              admin_graphql_api_id: "gid://shopify/LineItem/16437775106363",
              attributed_staffs: [],
              current_quantity: 1,
              fulfillable_quantity: 0,
              fulfillment_service: "manual",
              fulfillment_status: "fulfilled",
              gift_card: false,
              grams: 0,
              name: "Medium Box",
              price: "100.00",
              price_set: {
                shop_money: {
                  amount: "100.00",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "100.00",
                  currency_code: "INR",
                },
              },
              product_exists: true,
              product_id: 10003371721019,
              properties: [],
              quantity: 1,
              requires_shipping: true,
              sku: "",
              taxable: true,
              title: "Medium Box",
              total_discount: "0.00",
              total_discount_set: {
                shop_money: {
                  amount: "0.00",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "0.00",
                  currency_code: "INR",
                },
              },
              variant_id: 49981910024507,
              variant_inventory_management: "shopify",
              variant_title: null,
              vendor: "giftclub",
              tax_lines: [
                {
                  channel_liable: false,
                  price: "15.26",
                  price_set: {
                    shop_money: {
                      amount: "15.26",
                      currency_code: "INR",
                    },
                    presentment_money: {
                      amount: "15.26",
                      currency_code: "INR",
                    },
                  },
                  rate: 0.18,
                  title: "IGST",
                },
              ],
              duties: [],
              discount_allocations: [],
            },
            {
              id: 16437775139131,
              admin_graphql_api_id: "gid://shopify/LineItem/16437775139131",
              attributed_staffs: [],
              current_quantity: 1,
              fulfillable_quantity: 0,
              fulfillment_service: "manual",
              fulfillment_status: "fulfilled",
              gift_card: false,
              grams: 0,
              name: "Give It A Whirl Earrings - Acrylic",
              price: "300.00",
              price_set: {
                shop_money: {
                  amount: "300.00",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "300.00",
                  currency_code: "INR",
                },
              },
              product_exists: true,
              product_id: 10003285901627,
              properties: [],
              quantity: 1,
              requires_shipping: true,
              sku: null,
              taxable: true,
              title: "Give It A Whirl Earrings",
              total_discount: "0.00",
              total_discount_set: {
                shop_money: {
                  amount: "0.00",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "0.00",
                  currency_code: "INR",
                },
              },
              variant_id: 49981606428987,
              variant_inventory_management: "shopify",
              variant_title: "Acrylic",
              vendor: "merchant-prod-2",
              tax_lines: [
                {
                  channel_liable: false,
                  price: "45.76",
                  price_set: {
                    shop_money: {
                      amount: "45.76",
                      currency_code: "INR",
                    },
                    presentment_money: {
                      amount: "45.76",
                      currency_code: "INR",
                    },
                  },
                  rate: 0.18,
                  title: "IGST",
                },
              ],
              duties: [],
              discount_allocations: [],
            },
          ],
        },
      ],
      line_items: [
        {
          id: 16437775106363,
          admin_graphql_api_id: "gid://shopify/LineItem/16437775106363",
          attributed_staffs: [],
          current_quantity: 1,
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 0,
          name: "Medium Box",
          price: "100.00",
          price_set: {
            shop_money: {
              amount: "100.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "100.00",
              currency_code: "INR",
            },
          },
          product_exists: true,
          product_id: 10003371721019,
          properties: [],
          quantity: 1,
          requires_shipping: true,
          sales_line_item_group_id: null,
          sku: "",
          taxable: true,
          title: "Medium Box",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          variant_id: 49981910024507,
          variant_inventory_management: "shopify",
          variant_title: null,
          vendor: "giftclub",
          tax_lines: [
            {
              channel_liable: false,
              price: "15.26",
              price_set: {
                shop_money: {
                  amount: "15.26",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "15.26",
                  currency_code: "INR",
                },
              },
              rate: 0.18,
              title: "IGST",
            },
          ],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 16437775139131,
          admin_graphql_api_id: "gid://shopify/LineItem/16437775139131",
          attributed_staffs: [],
          current_quantity: 1,
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 0,
          name: "Give It A Whirl Earrings - Acrylic",
          price: "300.00",
          price_set: {
            shop_money: {
              amount: "300.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "300.00",
              currency_code: "INR",
            },
          },
          product_exists: true,
          product_id: 10003285901627,
          properties: [],
          quantity: 1,
          requires_shipping: true,
          sales_line_item_group_id: null,
          sku: null,
          taxable: true,
          title: "Give It A Whirl Earrings",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          variant_id: 49981606428987,
          variant_inventory_management: "shopify",
          variant_title: "Acrylic",
          vendor: "merchant-prod-2",
          tax_lines: [
            {
              channel_liable: false,
              price: "45.76",
              price_set: {
                shop_money: {
                  amount: "45.76",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "45.76",
                  currency_code: "INR",
                },
              },
              rate: 0.18,
              title: "IGST",
            },
          ],
          duties: [],
          discount_allocations: [],
        },
      ],
      payment_terms: null,
      refunds: [],
      shipping_address: {
        first_name: null,
        address1: "Sector D Vasant Kunj",
        phone: null,
        city: "New Delhi",
        zip: "110070",
        province: "Delhi",
        country: "India",
        last_name: "",
        address2: null,
        company: null,
        latitude: 28.5254842,
        longitude: 77.1433249,
        name: "",
        country_code: "IN",
        province_code: "DL",
      },
      shipping_lines: [],
      returns: [],
    },
    metadata: {
      "Content-Type": "application/json",
      "X-Shopify-Topic": "orders/fulfilled",
      "X-Shopify-Shop-Domain": "merchant-prod-2.myshopify.com",
      "X-Shopify-Order-Id": "6527573459259",
      "X-Shopify-Test": "false",
      "X-Shopify-Hmac-SHA256": "aJek7Pb+8mOoPkk0Vt16BBu8rsW4tyHJT6YJQ71nnj8=",
      "X-Shopify-Webhook-Id": "e1d5ff3e-c6b2-44a8-9d5a-efcbb0468dbb",
      "X-Shopify-API-Version": "2025-01",
      "X-Shopify-Event-Id": "fb236b52-41dd-429e-827d-932ffc02874c",
      "X-Shopify-Triggered-At": "2025-01-31T10:46:14.307259733Z",
    },
  },
};

export const CREATE_PRODUCT = {
  version: "0",
  id: "5d3aa06d-4178-0a99-6907-4160ac555293",
  "detail-type": "shopifyWebhook",
  source:
    "aws.partner/shopify.com/202204020737/Giftclub_dev-Giftclub_Merchant_Dev",
  account: "442426894654",
  time: "2025-01-23T08:10:49Z",
  region: "ap-south-1",
  resources: [],
  detail: {
    payload: {
      admin_graphql_api_id: "gid://shopify/Product/9616657023266",
      body_html: "<p>xyz</p>",
      created_at: "2025-01-23T03:10:46-05:00",
      handle: "test-product",
      id: 9616657023266,
      product_type: "",
      published_at: "2025-01-23T03:10:46-05:00",
      template_suffix: "",
      title: "test product",
      updated_at: "2025-01-23T03:10:48-05:00",
      vendor: "giftclub-merchant-dev",
      status: "active",
      published_scope: "global",
      tags: "",
      variants: [
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571497345314",
          barcode: "",
          compare_at_price: "200.00",
          created_at: "2025-01-23T03:10:47-05:00",
          id: 49571497345314,
          inventory_policy: "deny",
          position: 2,
          price: "3000.00",
          product_id: 9616657023266,
          sku: "",
          taxable: true,
          title: "Red",
          updated_at: "2025-01-23T03:10:47-05:00",
          option1: "Red",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597438419234,
          inventory_quantity: 0,
          old_inventory_quantity: 0,
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571497378082",
          barcode: "",
          compare_at_price: "200.00",
          created_at: "2025-01-23T03:10:47-05:00",
          id: 49571497378082,
          inventory_policy: "deny",
          position: 3,
          price: "3000.00",
          product_id: 9616657023266,
          sku: "",
          taxable: true,
          title: "Bronze",
          updated_at: "2025-01-23T03:10:47-05:00",
          option1: "Bronze",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597438452002,
          inventory_quantity: 0,
          old_inventory_quantity: 0,
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571497410850",
          barcode: "",
          compare_at_price: "200.00",
          created_at: "2025-01-23T03:10:47-05:00",
          id: 49571497410850,
          inventory_policy: "deny",
          position: 4,
          price: "3000.00",
          product_id: 9616657023266,
          sku: "",
          taxable: true,
          title: "Brown",
          updated_at: "2025-01-23T03:10:47-05:00",
          option1: "Brown",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597438484770,
          inventory_quantity: 0,
          old_inventory_quantity: 0,
        },
      ],
      options: [
        {
          name: "Color",
          id: 12072077000994,
          product_id: 9616657023266,
          position: 1,
          values: ["Red", "Bronze", "Brown"],
        },
      ],
      images: [],
      image: null,
      media: [],
      variant_gids: [
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571497345314",
          updated_at: "2025-01-23T08:10:47.000Z",
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571497378082",
          updated_at: "2025-01-23T08:10:47.000Z",
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571497410850",
          updated_at: "2025-01-23T08:10:47.000Z",
        },
      ],
      has_variants_that_requires_components: false,
      category: {
        admin_graphql_api_id: "gid://shopify/TaxonomyCategory/aa-2-14-6",
        name: "Hair Pins, Claws & Clips",
        full_name:
          "Apparel & Accessories > Clothing Accessories > Hair Accessories > Hair Pins, Claws & Clips",
      },
    },
    metadata: {
      "Content-Type": "application/json",
      "X-Shopify-Topic": "products/create",
      "X-Shopify-Shop-Domain": "giftkart-merchant-dev.myshopify.com",
      "X-Shopify-Product-Id": "9616657023266",
      "X-Shopify-Hmac-SHA256": "wBy5qHwvxvR+nKNDIrYdpaWVb55lHzIcNPsDGaabOas=",
      "X-Shopify-Webhook-Id": "d03ffe12-e2b6-4a97-aacf-5fde6cfbb9f5",
      "X-Shopify-API-Version": "2024-10",
      "X-Shopify-Event-Id": "598ac5b6-7582-4cfa-bea2-301fcf39df55",
      "X-Shopify-Triggered-At": "2025-01-23T08:10:47.076293528Z",
    },
  },
};

export const PRODUCT_UPDATE = {
  version: "0",
  id: "dbab180e-2bee-2e7a-2a47-d7534f1d27e9",
  "detail-type": "shopifyWebhook",
  source:
    "aws.partner/shopify.com/202204020737/Giftclub_dev-Giftclub_Merchant_Dev",
  account: "442426894654",
  time: "2025-01-23T08:45:24Z",
  region: "ap-south-1",
  resources: [],
  detail: {
    payload: {
      admin_graphql_api_id: "gid://shopify/Product/9616711090466",
      body_html:
        "<p>The upper is set on a striped cotton base, featuring a moody colour palette. The same hues of terracotta, maroon, blue and eggshell are used to create a checkered pattern with threadwork embroidery to add some texture. The upper is further highlighted with iridescent sequins. The back has a plain maroon silk base, with gold twine and sequin lace helping accentuate the design.</p>",
      created_at: "2025-01-23T03:45:21-05:00",
      handle: "magnum",
      id: 9616711090466,
      product_type: "",
      published_at: "2025-01-23T03:45:21-05:00",
      template_suffix: "",
      title: "Magnum",
      updated_at: "2025-01-23T03:45:23-05:00",
      vendor: "giftclub-merchant-dev",
      status: "active",
      published_scope: "global",
      tags: "",
      variants: [
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630350626",
          barcode: "",
          compare_at_price: "2699.00",
          created_at: "2025-01-23T03:45:22-05:00",
          id: 49571630350626,
          inventory_policy: "deny",
          position: 2,
          price: "1899.00",
          product_id: 9616711090466,
          sku: "",
          taxable: true,
          title: "Black",
          updated_at: "2025-01-23T03:45:22-05:00",
          option1: "Black",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597571424546,
          inventory_quantity: 30,
          old_inventory_quantity: 30,
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630383394",
          barcode: "",
          compare_at_price: "2699.00",
          created_at: "2025-01-23T03:45:22-05:00",
          id: 49571630383394,
          inventory_policy: "deny",
          position: 3,
          price: "1899.00",
          product_id: 9616711090466,
          sku: "",
          taxable: true,
          title: "Blue",
          updated_at: "2025-01-23T03:45:22-05:00",
          option1: "Blue",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597571457314,
          inventory_quantity: 20,
          old_inventory_quantity: 20,
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630416162",
          barcode: "",
          compare_at_price: "2699.00",
          created_at: "2025-01-23T03:45:22-05:00",
          id: 49571630416162,
          inventory_policy: "deny",
          position: 4,
          price: "1899.00",
          product_id: 9616711090466,
          sku: "",
          taxable: true,
          title: "Red",
          updated_at: "2025-01-23T03:45:22-05:00",
          option1: "Red",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597571490082,
          inventory_quantity: 10,
          old_inventory_quantity: 10,
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630448930",
          barcode: "",
          compare_at_price: "2699.00",
          created_at: "2025-01-23T03:45:22-05:00",
          id: 49571630448930,
          inventory_policy: "deny",
          position: 5,
          price: "1899.00",
          product_id: 9616711090466,
          sku: "",
          taxable: true,
          title: "Pink",
          updated_at: "2025-01-23T03:45:22-05:00",
          option1: "Pink",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597571522850,
          inventory_quantity: 10,
          old_inventory_quantity: 10,
        },
      ],
      options: [
        {
          name: "Color",
          id: 12072158560546,
          product_id: 9616711090466,
          position: 1,
          values: ["Black", "Blue", "Red", "Pink"],
        },
      ],
      images: [
        {
          id: 59020646973730,
          product_id: 9616711090466,
          position: 1,
          created_at: "2025-01-23T03:44:07-05:00",
          updated_at: "2025-01-23T03:45:21-05:00",
          alt: null,
          width: 1000,
          height: 1000,
          src: "https://cdn.shopify.com/s/files/1/0921/3732/4834/files/magnum-563468.jpg?v=1737621848",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/59020646973730",
        },
      ],
      image: {
        id: 59020646973730,
        product_id: 9616711090466,
        position: 1,
        created_at: "2025-01-23T03:44:07-05:00",
        updated_at: "2025-01-23T03:45:21-05:00",
        alt: null,
        width: 1000,
        height: 1000,
        src: "https://cdn.shopify.com/s/files/1/0921/3732/4834/files/magnum-563468.jpg?v=1737621848",
        variant_ids: [],
        admin_graphql_api_id: "gid://shopify/ProductImage/59020646973730",
      },
      media: [
        {
          id: 50951981826338,
          product_id: 9616711090466,
          position: 1,
          created_at: "2025-01-23T03:44:07-05:00",
          updated_at: "2025-01-23T03:45:21-05:00",
          alt: null,
          status: "READY",
          media_content_type: "IMAGE",
          preview_image: {
            width: 1000,
            height: 1000,
            src: "https://cdn.shopify.com/s/files/1/0921/3732/4834/files/magnum-563468.jpg?v=1737621848",
            status: "READY",
          },
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/MediaImage/50951981826338",
        },
      ],
      variant_gids: [
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630350626",
          updated_at: "2025-01-23T08:45:22.000Z",
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630383394",
          updated_at: "2025-01-23T08:45:22.000Z",
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630416162",
          updated_at: "2025-01-23T08:45:22.000Z",
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630448930",
          updated_at: "2025-01-23T08:45:22.000Z",
        },
      ],
      has_variants_that_requires_components: false,
      category: {
        admin_graphql_api_id: "gid://shopify/TaxonomyCategory/aa-8-9",
        name: "Flats",
        full_name: "Apparel & Accessories > Shoes > Flats",
      },
    },
    metadata: {
      "Content-Type": "application/json",
      "X-Shopify-Topic": "products/update",
      "X-Shopify-Shop-Domain": "giftkart-merchant-dev.myshopify.com",
      "X-Shopify-Product-Id": "9616711090466",
      "X-Shopify-Hmac-SHA256": "sJIkhKT38a/OVm2jMlQq5JXy/2aZlAfnwpa3ZVIz5do=",
      "X-Shopify-Webhook-Id": "90452f36-1775-42c3-b580-ad75cb3fdc05",
      "X-Shopify-API-Version": "2024-10",
      "X-Shopify-Event-Id": "8f5ea559-3f19-4c96-8977-74fc07ed6fee",
      "X-Shopify-Triggered-At": "2025-01-23T08:45:23.163369928Z",
    },
  },
};

export const APP_UNINSTALL = {
  version: "0",
  id: "7f54051a-8835-d03d-a89a-6f00e73d89fc",
  "detail-type": "shopifyWebhook",
  source:
    "aws.partner/shopify.com/202204020737/Giftclub_dev-Giftclub_Merchant_Dev",
  account: "442426894654",
  time: "2025-01-31T07:25:27Z",
  region: "ap-south-1",
  resources: [],
  detail: {
    payload: {
      id: 92137324834,
      name: "giftclub-merchant-dev",
      email: "lakshya@giftkart.ai",
      domain: "giftkart-merchant-dev.myshopify.com",
      province: null,
      country: "IN",
      address1: null,
      zip: null,
      city: null,
      source: null,
      phone: null,
      latitude: null,
      longitude: null,
      primary_locale: "en",
      address2: null,
      created_at: "2024-12-23T01:56:03-05:00",
      updated_at: "2025-01-27T22:06:23-05:00",
      country_code: "IN",
      country_name: "India",
      currency: "INR",
      customer_email: "lakshya@giftkart.ai",
      timezone: "(GMT-05:00) America/New_York",
      iana_timezone: "America/New_York",
      shop_owner: "Lakshya Tiwari",
      money_format: "Rs. {{amount}}",
      money_with_currency_format: "Rs. {{amount}}",
      weight_unit: "kg",
      province_code: null,
      taxes_included: true,
      auto_configure_tax_inclusivity: false,
      tax_shipping: false,
      county_taxes: true,
      plan_display_name: "Development",
      plan_name: "affiliate",
      has_discounts: false,
      has_gift_cards: false,
      myshopify_domain: "giftkart-merchant-dev.myshopify.com",
      google_apps_domain: null,
      google_apps_login_enabled: null,
      money_in_emails_format: "Rs. {{amount}}",
      money_with_currency_in_emails_format: "Rs. {{amount}}",
      eligible_for_payments: false,
      requires_extra_payments_agreement: false,
      password_enabled: true,
      has_storefront: true,
      finances: true,
      primary_location_id: 104064745762,
      checkout_api_supported: false,
      multi_location_enabled: true,
      setup_required: false,
      pre_launch_enabled: false,
      enabled_presentment_currencies: ["INR"],
      marketing_sms_consent_enabled_at_checkout: false,
      transactional_sms_disabled: true,
    },
    metadata: {
      "Content-Type": "application/json",
      "X-Shopify-Topic": "app/uninstalled",
      "X-Shopify-Shop-Domain": "giftkart-merchant-dev.myshopify.com",
      "X-Shopify-Hmac-SHA256": "eMDSYdcSowTX+DEe3Mqs5AIiJH9QGVmdXcc/htJ8Obg=",
      "X-Shopify-Webhook-Id": "6b60eaf8-e30f-4e19-b4da-7c6927ce72c5",
      "X-Shopify-API-Version": "2024-10",
      "X-Shopify-Event-Id": "7e05ae51-d39d-4350-a55c-bed3b4a67f24",
      "X-Shopify-Triggered-At": "2025-01-31T07:25:25.539972216Z",
    },
  },
};

export const ORDER_PAID = {
  version: "0",
  id: "e1a7d6c6-d01a-5cde-977c-6378b90f8215",
  "detail-type": "shopifyWebhook",
  source:
    "aws.partner/shopify.com/206697234433/Giftclub_prod-Giftclub_Merchant_prod",
  account: "442426894654",
  time: "2025-01-31T14:04:22Z",
  region: "ap-south-1",
  resources: [],
  detail: {
    payload: {
      id: 5977370362072,
      admin_graphql_api_id: "gid://shopify/Order/5977370362072",
      app_id: 206697234433,
      browser_ip: "13.203.96.159",
      buyer_accepts_marketing: false,
      cancel_reason: null,
      cancelled_at: null,
      cart_token: null,
      checkout_id: 36377439043800,
      checkout_token: "f9bb4bbd511bf9c6a348d6c246134eb2",
      client_details: {
        accept_language: "*",
        browser_height: null,
        browser_ip: "13.203.96.159",
        browser_width: null,
        session_hash: null,
        user_agent: "node",
      },
      closed_at: null,
      company: null,
      confirmation_number: "V398DNP78",
      confirmed: true,
      contact_email: "lakshya@giftkart.ai",
      created_at: "2025-01-31T09:03:34-05:00",
      currency: "INR",
      current_shipping_price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      current_subtotal_price: "2649.00",
      current_subtotal_price_set: {
        shop_money: {
          amount: "2649.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "2649.00",
          currency_code: "INR",
        },
      },
      current_total_additional_fees_set: null,
      current_total_discounts: "0.00",
      current_total_discounts_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      current_total_duties_set: null,
      current_total_price: "2649.00",
      current_total_price_set: {
        shop_money: {
          amount: "2649.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "2649.00",
          currency_code: "INR",
        },
      },
      current_total_tax: "404.08",
      current_total_tax_set: {
        shop_money: {
          amount: "404.08",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "404.08",
          currency_code: "INR",
        },
      },
      customer_locale: "en",
      device_id: null,
      discount_codes: [],
      duties_included: false,
      email: "lakshya@giftkart.ai",
      estimated_taxes: false,
      financial_status: "paid",
      fulfillment_status: null,
      landing_site: null,
      landing_site_ref: null,
      location_id: null,
      merchant_business_entity_id: "MTcyODYwOTkxNzA0",
      merchant_of_record_app_id: null,
      name: "#1049",
      note: null,
      note_attributes: [],
      number: 49,
      order_number: 1049,
      order_status_url:
        "https://giftclub-merchant-prod.myshopify.com/72860991704/orders/4bdeb298cd6df75cca2c7afddb740e7e/authenticate?key=ce5d928df751128acd52691cae195001",
      original_total_additional_fees_set: null,
      original_total_duties_set: null,
      payment_gateway_names: ["manual"],
      phone: null,
      po_number: null,
      presentment_currency: "INR",
      processed_at: "2025-01-31T09:03:33-05:00",
      reference: null,
      referring_site: null,
      source_identifier: null,
      source_name: "206697234433",
      source_url: null,
      subtotal_price: "2649.00",
      subtotal_price_set: {
        shop_money: {
          amount: "2649.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "2649.00",
          currency_code: "INR",
        },
      },
      tags: "generated_via_giftclub",
      tax_exempt: false,
      tax_lines: [
        {
          price: "404.08",
          rate: 0.18,
          title: "IGST",
          price_set: {
            shop_money: {
              amount: "404.08",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "404.08",
              currency_code: "INR",
            },
          },
          channel_liable: false,
        },
      ],
      taxes_included: true,
      test: false,
      token: "4bdeb298cd6df75cca2c7afddb740e7e",
      total_cash_rounding_payment_adjustment_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_cash_rounding_refund_adjustment_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_discounts: "0.00",
      total_discounts_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_line_items_price: "2649.00",
      total_line_items_price_set: {
        shop_money: {
          amount: "2649.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "2649.00",
          currency_code: "INR",
        },
      },
      total_outstanding: "0.00",
      total_price: "2649.00",
      total_price_set: {
        shop_money: {
          amount: "2649.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "2649.00",
          currency_code: "INR",
        },
      },
      total_shipping_price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_tax: "404.08",
      total_tax_set: {
        shop_money: {
          amount: "404.08",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "404.08",
          currency_code: "INR",
        },
      },
      total_tip_received: "0.00",
      total_weight: 0,
      updated_at: "2025-01-31T09:04:20-05:00",
      user_id: null,
      billing_address: null,
      customer: {
        id: 7884958892248,
        email: "lakshya@giftkart.ai",
        created_at: "2025-01-10T08:41:57-05:00",
        updated_at: "2025-01-31T09:03:34-05:00",
        first_name: null,
        last_name: "",
        state: "disabled",
        note: null,
        verified_email: true,
        multipass_identifier: null,
        tax_exempt: false,
        phone: null,
        currency: "INR",
        tax_exemptions: [],
        admin_graphql_api_id: "gid://shopify/Customer/7884958892248",
        default_address: {
          id: 9299106365656,
          customer_id: 7884958892248,
          first_name: null,
          last_name: "",
          company: null,
          address1: "Sector D Vasant Kunj",
          address2: null,
          city: "New Delhi",
          province: "Delhi",
          country: "India",
          zip: "110070",
          phone: null,
          name: "",
          province_code: "DL",
          country_code: "IN",
          country_name: "India",
          default: true,
        },
      },
      discount_applications: [],
      fulfillments: [],
      line_items: [
        {
          id: 14618485850328,
          admin_graphql_api_id: "gid://shopify/LineItem/14618485850328",
          attributed_staffs: [],
          current_quantity: 1,
          fulfillable_quantity: 1,
          fulfillment_service: "manual",
          fulfillment_status: null,
          gift_card: false,
          grams: 0,
          name: "Large Box",
          price: "150.00",
          price_set: {
            shop_money: {
              amount: "150.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "150.00",
              currency_code: "INR",
            },
          },
          product_exists: true,
          product_id: 8790403285208,
          properties: [],
          quantity: 1,
          requires_shipping: true,
          sales_line_item_group_id: null,
          sku: "",
          taxable: true,
          title: "Large Box",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          variant_id: 50057713778904,
          variant_inventory_management: "shopify",
          variant_title: null,
          vendor: "giftclub",
          tax_lines: [
            {
              channel_liable: false,
              price: "22.88",
              price_set: {
                shop_money: {
                  amount: "22.88",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "22.88",
                  currency_code: "INR",
                },
              },
              rate: 0.18,
              title: "IGST",
            },
          ],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 14618485883096,
          admin_graphql_api_id: "gid://shopify/LineItem/14618485883096",
          attributed_staffs: [],
          current_quantity: 1,
          fulfillable_quantity: 1,
          fulfillment_service: "manual",
          fulfillment_status: null,
          gift_card: false,
          grams: 0,
          name: "Snitch & Vanya Bundle - M / XL",
          price: "2499.00",
          price_set: {
            shop_money: {
              amount: "2499.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "2499.00",
              currency_code: "INR",
            },
          },
          product_exists: true,
          product_id: 8789806121176,
          properties: [],
          quantity: 1,
          requires_shipping: true,
          sales_line_item_group_id: null,
          sku: "",
          taxable: true,
          title: "Snitch & Vanya Bundle",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          variant_id: 50055471530200,
          variant_inventory_management: null,
          variant_title: "M / XL",
          vendor: "giftclub-merchant-prod",
          tax_lines: [
            {
              channel_liable: false,
              price: "381.20",
              price_set: {
                shop_money: {
                  amount: "381.20",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "381.20",
                  currency_code: "INR",
                },
              },
              rate: 0.18,
              title: "IGST",
            },
          ],
          duties: [],
          discount_allocations: [],
        },
      ],
      payment_terms: null,
      refunds: [],
      shipping_address: {
        first_name: null,
        address1: "Sector D Vasant Kunj",
        phone: null,
        city: "New Delhi",
        zip: "110070",
        province: "Delhi",
        country: "India",
        last_name: "",
        address2: null,
        company: null,
        latitude: 28.5254842,
        longitude: 77.1433249,
        name: "",
        country_code: "IN",
        province_code: "DL",
      },
      shipping_lines: [],
      returns: [],
    },
    metadata: {
      "Content-Type": "application/json",
      "X-Shopify-Topic": "orders/paid",
      "X-Shopify-Shop-Domain": "giftclub-merchant-prod.myshopify.com",
      "X-Shopify-Order-Id": "5977370362072",
      "X-Shopify-Test": "false",
      "X-Shopify-Hmac-SHA256": "ZQnu+EZzDRE2LXRrA6K2RLTHK8/nrqk174KyPrHTZgg=",
      "X-Shopify-Webhook-Id": "97f1be83-ce79-41d7-aaf2-067cf3683cae",
      "X-Shopify-API-Version": "2025-01",
      "X-Shopify-Event-Id": "7063a3d8-35ba-422b-ba8b-7d51d7853703",
      "X-Shopify-Triggered-At": "2025-01-31T14:04:20.096329843Z",
    },
  },
};
