export const ORDER_CREATE_PAYLOAD = {
  version: "0",
  id: "2b7cc843-a78e-ae2d-78fa-f2ae43c7b01e",
  "detail-type": "shopifyWebhook",
  source:
    "aws.partner/shopify.com/202194976769/Giftclub_dev-Giftclub_marketplace_dev",
  account: "442426894654",
  time: "2025-01-03T07:25:56Z",
  region: "ap-south-1",
  resources: [],
  detail: {
    payload: {
      id: 5870059028692,
      admin_graphql_api_id: "gid://shopify/Order/5870059028692",
      app_id: 580111,
      browser_ip: "2401:4900:1c68:d38f:a154:2f54:452f:9653",
      buyer_accepts_marketing: false,
      cancel_reason: null,
      cancelled_at: null,
      cart_token: "Z2NwLXVzLWVhc3QxOjAxSkdOR1ZZVkc1Uk5OM1k5QVQwTVRUSjBI",
      checkout_id: 37004269420756,
      checkout_token: "8ed71d58b11e13da546a3fb5a95b83c2",
      client_details: {
        accept_language: "en-IN",
        browser_height: null,
        browser_ip: "2401:4900:1c68:d38f:a154:2f54:452f:9653",
        browser_width: null,
        session_hash: null,
        user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
      },
      closed_at: null,
      company: null,
      confirmation_number: "0AK8U5Q1R",
      confirmed: true,
      contact_email: "lakshya@giftkart.ai",
      created_at: "2025-01-03T02:25:53-05:00",
      currency: "INR",
      current_shipping_price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      current_subtotal_price: "553.00",
      current_subtotal_price_set: {
        shop_money: {
          amount: "553.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "553.00",
          currency_code: "INR",
        },
      },
      current_total_additional_fees_set: null,
      current_total_discounts: "0.00",
      current_total_discounts_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      current_total_duties_set: null,
      current_total_price: "652.54",
      current_total_price_set: {
        shop_money: {
          amount: "652.54",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "652.54",
          currency_code: "INR",
        },
      },
      current_total_tax: "99.54",
      current_total_tax_set: {
        shop_money: {
          amount: "99.54",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "99.54",
          currency_code: "INR",
        },
      },
      customer_locale: "en-IN",
      device_id: null,
      discount_codes: [],
      duties_included: false,
      email: "lakshya@giftkart.ai",
      estimated_taxes: false,
      financial_status: "paid",
      fulfillment_status: null,
      landing_site: "/",
      landing_site_ref: null,
      location_id: null,
      merchant_business_entity_id: "MTczNDQzNzA1MDQ0",
      merchant_of_record_app_id: null,
      name: "#1007",
      note: null,
      note_attributes: [],
      number: 7,
      order_number: 1007,
      order_status_url:
        "https://giftclub-marketplace-dev.myshopify.com/73443705044/orders/6ce93bb2f86868fb1889b28d25c66f9b/authenticate?key=6cda0b754dbe13b5985bd85b3963b774",
      original_total_additional_fees_set: null,
      original_total_duties_set: null,
      payment_gateway_names: ["bogus"],
      phone: null,
      po_number: null,
      presentment_currency: "INR",
      processed_at: "2025-01-03T02:25:52-05:00",
      reference: null,
      referring_site: "",
      source_identifier: null,
      source_name: "web",
      source_url: null,
      subtotal_price: "553.00",
      subtotal_price_set: {
        shop_money: {
          amount: "553.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "553.00",
          currency_code: "INR",
        },
      },
      tags: "",
      tax_exempt: false,
      tax_lines: [
        {
          price: "99.54",
          rate: 0.18,
          title: "IGST",
          price_set: {
            shop_money: {
              amount: "99.54",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "99.54",
              currency_code: "INR",
            },
          },
          channel_liable: false,
        },
      ],
      taxes_included: false,
      test: true,
      token: "6ce93bb2f86868fb1889b28d25c66f9b",
      total_cash_rounding_payment_adjustment_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_cash_rounding_refund_adjustment_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_discounts: "0.00",
      total_discounts_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_line_items_price: "553.00",
      total_line_items_price_set: {
        shop_money: {
          amount: "553.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "553.00",
          currency_code: "INR",
        },
      },
      total_outstanding: "0.00",
      total_price: "652.54",
      total_price_set: {
        shop_money: {
          amount: "652.54",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "652.54",
          currency_code: "INR",
        },
      },
      total_shipping_price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_tax: "99.54",
      total_tax_set: {
        shop_money: {
          amount: "99.54",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "99.54",
          currency_code: "INR",
        },
      },
      total_tip_received: "0.00",
      total_weight: 0,
      updated_at: "2025-01-03T02:25:54-05:00",
      user_id: null,
      billing_address: {
        first_name: "Lakshya",
        address1: "Sector D Vasant Kunj",
        phone: null,
        city: "New Delhi",
        zip: "110070",
        province: "Delhi",
        country: "India",
        last_name: "dev",
        address2: null,
        company: null,
        latitude: 28.5254842,
        longitude: 77.1433249,
        name: "Lakshya dev",
        country_code: "IN",
        province_code: "DL",
      },
      customer: {
        id: 7712945897684,
        email: "lakshya@giftkart.ai",
        created_at: "2025-01-02T02:56:32-05:00",
        updated_at: "2025-01-03T02:25:54-05:00",
        first_name: "Lakshya",
        last_name: "dev",
        state: "disabled",
        note: null,
        verified_email: true,
        multipass_identifier: null,
        tax_exempt: false,
        phone: null,
        email_marketing_consent: {
          state: "not_subscribed",
          opt_in_level: "single_opt_in",
          consent_updated_at: null,
        },
        sms_marketing_consent: null,
        tags: "",
        currency: "INR",
        tax_exemptions: [],
        admin_graphql_api_id: "gid://shopify/Customer/7712945897684",
        default_address: {
          id: 9201000054996,
          customer_id: 7712945897684,
          first_name: "Lakshya",
          last_name: "dev",
          company: null,
          address1: "Sector D Vasant Kunj",
          address2: null,
          city: "New Delhi",
          province: "Delhi",
          country: "India",
          zip: "110070",
          phone: null,
          name: "Lakshya dev",
          province_code: "DL",
          country_code: "IN",
          country_name: "India",
          default: true,
        },
      },
      discount_applications: [],
      fulfillments: [],
      line_items: [
        {
          id: 14371809951956,
          admin_graphql_api_id: "gid://shopify/LineItem/14371809951956",
          attributed_staffs: [],
          current_quantity: 1,
          fulfillable_quantity: 1,
          fulfillment_service: "manual",
          fulfillment_status: null,
          gift_card: false,
          grams: 0,
          name: "Eric Beasley - With Packaging",
          price: "553.00",
          price_set: {
            shop_money: {
              amount: "553.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "553.00",
              currency_code: "INR",
            },
          },
          product_exists: true,
          product_id: 8725646770388,
          properties: [],
          quantity: 1,
          requires_shipping: true,
          sku: "Soluta vero consequa_P",
          taxable: true,
          title: "Eric Beasley",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          variant_id: 45956901667028,
          variant_inventory_management: "shopify",
          variant_title: "With Packaging",
          vendor: "Levi Oneil",
          tax_lines: [
            {
              channel_liable: false,
              price: "99.54",
              price_set: {
                shop_money: {
                  amount: "99.54",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "99.54",
                  currency_code: "INR",
                },
              },
              rate: 0.18,
              title: "IGST",
            },
          ],
          duties: [],
          discount_allocations: [],
        },
      ],
      payment_terms: null,
      refunds: [],
      shipping_address: {
        first_name: "Lakshya",
        address1: "Sector D Vasant Kunj",
        phone: null,
        city: "New Delhi",
        zip: "110070",
        province: "Delhi",
        country: "India",
        last_name: "dev",
        address2: null,
        company: null,
        latitude: null,
        longitude: null,
        name: "Lakshya dev",
        country_code: "IN",
        province_code: "DL",
      },
      shipping_lines: [
        {
          id: 4721899045076,
          carrier_identifier: null,
          code: "Standard",
          current_discounted_price_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          discounted_price: "0.00",
          discounted_price_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          is_removed: false,
          phone: null,
          price: "0.00",
          price_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          requested_fulfillment_service_id: null,
          source: "shopify",
          title: "Standard",
          tax_lines: [],
          discount_allocations: [],
        },
      ],
      returns: [],
    },
    metadata: {
      "Content-Type": "application/json",
      "X-Shopify-Topic": "orders/create",
      "X-Shopify-Shop-Domain": "giftclub-marketplace-dev.myshopify.com",
      "X-Shopify-Order-Id": "5870059028692",
      "X-Shopify-Test": "true",
      "X-Shopify-Hmac-SHA256": "yjvieNk0acS1FMVX7bfWtbVqvVR3Wt9MfxZ9L2hI9Uo=",
      "X-Shopify-Webhook-Id": "8932167f-ad05-4ecc-854a-969c2d5a8905",
      "X-Shopify-API-Version": "2024-10",
      "X-Shopify-Event-Id": "81541d1b-8360-4bb5-9c09-29e8eb23c502",
      "X-Shopify-Triggered-At": "2025-01-03T07:25:54.628387981Z",
    },
  },
};
