export const ORDER_CREATE_PAYLOAD = {
  version: "0",
  id: "9709b3a2-5c01-95d7-2a7c-00db18ae30ad",
  "detail-type": "shopifyWebhook",
  source: "aws.partner/shopify.com/201184116737/Giftclub_prod-Giftclub",
  account: "442426894654",
  time: "2025-01-30T13:55:19Z",
  region: "ap-south-1",
  resources: [],
  detail: {
    payload: {
      id: 6144935461105,
      admin_graphql_api_id: "gid://shopify/Order/6144935461105",
      app_id: 212419117057,
      browser_ip: "2401:4900:1c68:b40a:c85:d834:baf7:945d",
      buyer_accepts_marketing: true,
      cancel_reason: null,
      cancelled_at: null,
      cart_token:
        "Z2NwLWFzaWEtc291dGhlYXN0MTowMUpKVlFWUEQ4NVA4UldBNVpCTVdCVjhZNQ",
      checkout_id: 36350559551729,
      checkout_token: "e874b5e966382192f0a2d63b47c18f5d",
      client_details: {
        accept_language: "en-IN",
        browser_height: null,
        browser_ip: "2401:4900:1c68:b40a:c85:d834:baf7:945d",
        browser_width: null,
        session_hash: null,
        user_agent:
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
      },
      closed_at: null,
      confirmation_number: "8KEU41AH8",
      confirmed: true,
      contact_email: "lakshya@giftkart.ai",
      created_at: "2025-01-30T19:25:15+05:30",
      currency: "INR",
      current_shipping_price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      current_subtotal_price: "370.00",
      current_subtotal_price_set: {
        shop_money: {
          amount: "370.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "370.00",
          currency_code: "INR",
        },
      },
      current_total_additional_fees_set: null,
      current_total_discounts: "30.00",
      current_total_discounts_set: {
        shop_money: {
          amount: "30.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "30.00",
          currency_code: "INR",
        },
      },
      current_total_duties_set: null,
      current_total_price: "370.00",
      current_total_price_set: {
        shop_money: {
          amount: "370.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "370.00",
          currency_code: "INR",
        },
      },
      current_total_tax: "56.44",
      current_total_tax_set: {
        shop_money: {
          amount: "56.44",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "56.44",
          currency_code: "INR",
        },
      },
      customer_locale: "en-IN",
      device_id: null,
      discount_codes: [
        {
          code: "BB69",
          amount: "30.00",
          type: "percentage",
        },
      ],
      duties_included: false,
      email: "lakshya@giftkart.ai",
      estimated_taxes: false,
      financial_status: "pending",
      fulfillment_status: null,
      landing_site: "/pages/desktop-screen",
      landing_site_ref: null,
      location_id: null,
      merchant_business_entity_id: "MTcxODAwMzI0MzM3",
      merchant_of_record_app_id: null,
      name: "#1101",
      note: null,
      note_attributes: [],
      number: 101,
      order_number: 1101,
      order_status_url:
        "https://www.giftclub.ai/71800324337/orders/3810a6544bd72f569adae4efc1350ee8/authenticate?key=2c7de7e7afa7b51ebc74b1f92d27cd48",
      original_total_additional_fees_set: null,
      original_total_duties_set: null,
      payment_gateway_names: ["Cash on Delivery (COD)"],
      phone: null,
      po_number: null,
      presentment_currency: "INR",
      processed_at: "2025-01-30T19:25:14+05:30",
      reference: null,
      referring_site:
        "https://g82qgrn7ycmfg68m-71800324337.shopifypreview.com/",
      source_identifier: null,
      source_name: "212419117057",
      source_url: null,
      subtotal_price: "370.00",
      subtotal_price_set: {
        shop_money: {
          amount: "370.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "370.00",
          currency_code: "INR",
        },
      },
      tags: "",
      tax_exempt: false,
      tax_lines: [
        {
          price: "56.44",
          rate: 0.18,
          title: "IGST",
          price_set: {
            shop_money: {
              amount: "56.44",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "56.44",
              currency_code: "INR",
            },
          },
          channel_liable: false,
        },
      ],
      taxes_included: true,
      test: false,
      token: "3810a6544bd72f569adae4efc1350ee8",
      total_cash_rounding_payment_adjustment_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_cash_rounding_refund_adjustment_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_discounts: "30.00",
      total_discounts_set: {
        shop_money: {
          amount: "30.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "30.00",
          currency_code: "INR",
        },
      },
      total_line_items_price: "400.00",
      total_line_items_price_set: {
        shop_money: {
          amount: "400.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "400.00",
          currency_code: "INR",
        },
      },
      total_outstanding: "370.00",
      total_price: "370.00",
      total_price_set: {
        shop_money: {
          amount: "370.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "370.00",
          currency_code: "INR",
        },
      },
      total_shipping_price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_tax: "56.44",
      total_tax_set: {
        shop_money: {
          amount: "56.44",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "56.44",
          currency_code: "INR",
        },
      },
      total_tip_received: "0.00",
      total_weight: 0,
      updated_at: "2025-01-30T19:25:17+05:30",
      user_id: null,
      billing_address: {
        first_name: "Lakshya",
        address1: "Sector D Vasant Kunj",
        phone: null,
        city: "New Delhi",
        zip: "110070",
        province: "Delhi",
        country: "India",
        last_name: "Dev",
        address2: "appartment",
        company: null,
        latitude: null,
        longitude: null,
        name: "Lakshya Dev",
        country_code: "IN",
        province_code: "DL",
      },
      customer: {
        id: 7925853880561,
        email: "lakshya@giftkart.ai",
        created_at: "2024-12-21T16:11:48+05:30",
        updated_at: "2025-01-30T19:25:16+05:30",
        first_name: "Lakshya",
        last_name: "",
        state: "enabled",
        note: null,
        verified_email: true,
        multipass_identifier: null,
        tax_exempt: false,
        phone: "+919999297761",
        email_marketing_consent: {
          state: "subscribed",
          opt_in_level: "single_opt_in",
          consent_updated_at: "2025-01-14T00:41:40+05:30",
        },
        sms_marketing_consent: {
          state: "subscribed",
          opt_in_level: "single_opt_in",
          consent_updated_at: "2025-01-14T00:41:40+05:30",
          consent_collected_from: "OTHER",
        },
        tags: "acceptWhatsappMarketing",
        currency: "INR",
        tax_exemptions: [],
        admin_graphql_api_id: "gid://shopify/Customer/7925853880561",
        default_address: {
          id: 9355192140017,
          customer_id: 7925853880561,
          first_name: "Lakshya",
          last_name: "Dev",
          company: null,
          address1: "Sector D Vasant Kunj",
          address2: "appartment",
          city: "New Delhi",
          province: "Delhi",
          country: "India",
          zip: "110070",
          phone: null,
          name: "Lakshya Dev",
          province_code: "DL",
          country_code: "IN",
          country_name: "India",
          default: true,
        },
      },
      discount_applications: [
        {
          target_type: "line_item",
          type: "discount_code",
          value: "10.0",
          value_type: "percentage",
          allocation_method: "each",
          target_selection: "entitled",
          code: "BB69",
        },
      ],
      fulfillments: [],
      line_items: [
        {
          id: 14695833829617,
          admin_graphql_api_id: "gid://shopify/LineItem/14695833829617",
          attributed_staffs: [],
          current_quantity: 1,
          fulfillable_quantity: 1,
          fulfillment_service: "manual",
          fulfillment_status: null,
          gift_card: false,
          grams: 0,
          name: "Medium Box",
          price: "100.00",
          price_set: {
            shop_money: {
              amount: "100.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "100.00",
              currency_code: "INR",
            },
          },
          product_exists: true,
          product_id: 8740388700401,
          properties: [],
          quantity: 1,
          requires_shipping: true,
          sku: "",
          taxable: true,
          title: "Medium Box",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          variant_id: 45903263695089,
          variant_inventory_management: "shopify",
          variant_title: null,
          vendor: "giftclub",
          tax_lines: [
            {
              channel_liable: false,
              price: "15.25",
              price_set: {
                shop_money: {
                  amount: "15.25",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "15.25",
                  currency_code: "INR",
                },
              },
              rate: 0.18,
              title: "IGST",
            },
          ],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 14695833862385,
          admin_graphql_api_id: "gid://shopify/LineItem/14695833862385",
          attributed_staffs: [],
          current_quantity: 1,
          fulfillable_quantity: 1,
          fulfillment_service: "manual",
          fulfillment_status: null,
          gift_card: false,
          grams: 0,
          name: "Give It A Whirl Earrings - Alcantara",
          price: "300.00",
          price_set: {
            shop_money: {
              amount: "300.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "300.00",
              currency_code: "INR",
            },
          },
          product_exists: true,
          product_id: 8740367073521,
          properties: [
            {
              name: "packaging",
              value: "true",
            },
          ],
          quantity: 1,
          requires_shipping: true,
          sku: null,
          taxable: true,
          title: "Give It A Whirl Earrings",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          variant_id: 45903171944689,
          variant_inventory_management: "shopify",
          variant_title: "Alcantara",
          vendor: "merchant-prod-2",
          tax_lines: [
            {
              channel_liable: false,
              price: "41.19",
              price_set: {
                shop_money: {
                  amount: "41.19",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "41.19",
                  currency_code: "INR",
                },
              },
              rate: 0.18,
              title: "IGST",
            },
          ],
          duties: [],
          discount_allocations: [
            {
              amount: "30.00",
              amount_set: {
                shop_money: {
                  amount: "30.00",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "30.00",
                  currency_code: "INR",
                },
              },
              discount_application_index: 0,
            },
          ],
        },
      ],
      payment_terms: null,
      refunds: [],
      shipping_address: {
        first_name: "Lakshya",
        address1: "Sector D Vasant Kunj",
        phone: null,
        city: "New Delhi",
        zip: "110070",
        province: "Delhi",
        country: "India",
        last_name: "Dev",
        address2: "appartment",
        company: null,
        latitude: 28.5254842,
        longitude: 77.1433249,
        name: "Lakshya Dev",
        country_code: "IN",
        province_code: "DL",
      },
      shipping_lines: [
        {
          id: 4964033167601,
          carrier_identifier: null,
          code: "Standard",
          current_discounted_price_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          discounted_price: "0.00",
          discounted_price_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          is_removed: false,
          phone: null,
          price: "0.00",
          price_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          requested_fulfillment_service_id: null,
          source: "shopify",
          title: "Standard",
          tax_lines: [],
          discount_allocations: [],
        },
      ],
      returns: [],
    },
    metadata: {
      "Content-Type": "application/json",
      "X-Shopify-Topic": "orders/create",
      "X-Shopify-Shop-Domain": "cygzgc-jw.myshopify.com",
      "X-Shopify-Order-Id": "6144935461105",
      "X-Shopify-Test": "false",
      "X-Shopify-Hmac-SHA256": "7qLFOmYATVAXyZ++4RbekQVHTddVllILDUsgB47sbD4=",
      "X-Shopify-Webhook-Id": "5293f60a-ebf9-4da0-9d7d-47565dcc2eaf",
      "X-Shopify-API-Version": "2024-10",
      "X-Shopify-Event-Id": "1180c83b-1339-4b0c-90c7-220aeded805d",
      "X-Shopify-Triggered-At": "2025-01-30T13:55:17.282580734Z",
    },
  },
};

export const ORDER_FULFILLED = {
  version: "0",
  id: "af46fa91-5691-824f-709e-823096b636b4",
  "detail-type": "shopifyWebhook",
  source:
    "aws.partner/shopify.com/202204020737/Giftclub_dev-Giftclub_Merchant_Dev",
  account: "442426894654",
  time: "2025-01-16T11:26:49Z",
  region: "ap-south-1",
  resources: [],
  detail: {
    payload: {
      id: 6108091121954,
      admin_graphql_api_id: "gid://shopify/Order/6108091121954",
      app_id: 202204020737,
      browser_ip: "52.66.197.146",
      buyer_accepts_marketing: false,
      cancel_reason: null,
      cancelled_at: null,
      cart_token: null,
      checkout_id: 38109623058722,
      checkout_token: "fa3c28bb89742dcc753b004bbc06a2f8",
      client_details: {
        accept_language: "*",
        browser_height: null,
        browser_ip: "52.66.197.146",
        browser_width: null,
        session_hash: null,
        user_agent: "node",
      },
      closed_at: "2025-01-16T06:26:47-05:00",
      company: null,
      confirmation_number: "7E0TF9UV5",
      confirmed: true,
      contact_email: "lakshya@giftkart.ai",
      created_at: "2025-01-16T06:25:10-05:00",
      currency: "INR",
      current_shipping_price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      current_subtotal_price: "2100.00",
      current_subtotal_price_set: {
        shop_money: {
          amount: "2100.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "2100.00",
          currency_code: "INR",
        },
      },
      current_total_additional_fees_set: null,
      current_total_discounts: "0.00",
      current_total_discounts_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      current_total_duties_set: null,
      current_total_price: "2100.00",
      current_total_price_set: {
        shop_money: {
          amount: "2100.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "2100.00",
          currency_code: "INR",
        },
      },
      current_total_tax: "320.34",
      current_total_tax_set: {
        shop_money: {
          amount: "320.34",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "320.34",
          currency_code: "INR",
        },
      },
      customer_locale: "en",
      device_id: null,
      discount_codes: [],
      duties_included: false,
      email: "lakshya@giftkart.ai",
      estimated_taxes: false,
      financial_status: "paid",
      fulfillment_status: "fulfilled",
      landing_site: null,
      landing_site_ref: null,
      location_id: null,
      merchant_business_entity_id: "MTkyMTM3MzI0ODM0",
      merchant_of_record_app_id: null,
      name: "#1054",
      note: null,
      note_attributes: [
        {
          productID: "",
          giftWrapping: true,
        },
      ],
      number: 54,
      order_number: 1054,
      order_status_url:
        "https://giftkart-merchant-dev.myshopify.com/92137324834/orders/75c5c54d21f4299cf15f304ba1f68dd4/authenticate?key=026e8101df00d3cfe4aa639a7843336a",
      original_total_additional_fees_set: null,
      original_total_duties_set: null,
      payment_gateway_names: ["manual"],
      phone: null,
      po_number: null,
      presentment_currency: "INR",
      processed_at: "2025-01-16T06:25:10-05:00",
      reference: null,
      referring_site: null,
      source_identifier: null,
      source_name: "202204020737",
      source_url: null,
      subtotal_price: "2100.00",
      subtotal_price_set: {
        shop_money: {
          amount: "2100.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "2100.00",
          currency_code: "INR",
        },
      },
      tags: "generated_via_giftclub",
      tax_exempt: false,
      tax_lines: [
        {
          price: "320.34",
          rate: 0.18,
          title: "IGST",
          price_set: {
            shop_money: {
              amount: "320.34",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "320.34",
              currency_code: "INR",
            },
          },
          channel_liable: false,
        },
      ],
      taxes_included: true,
      test: false,
      token: "75c5c54d21f4299cf15f304ba1f68dd4",
      total_cash_rounding_payment_adjustment_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_cash_rounding_refund_adjustment_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_discounts: "0.00",
      total_discounts_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_line_items_price: "2100.00",
      total_line_items_price_set: {
        shop_money: {
          amount: "2100.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "2100.00",
          currency_code: "INR",
        },
      },
      total_outstanding: "0.00",
      total_price: "2100.00",
      total_price_set: {
        shop_money: {
          amount: "2100.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "2100.00",
          currency_code: "INR",
        },
      },
      total_shipping_price_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "INR",
        },
      },
      total_tax: "320.34",
      total_tax_set: {
        shop_money: {
          amount: "320.34",
          currency_code: "INR",
        },
        presentment_money: {
          amount: "320.34",
          currency_code: "INR",
        },
      },
      total_tip_received: "0.00",
      total_weight: 0,
      updated_at: "2025-01-16T06:26:47-05:00",
      user_id: null,
      billing_address: null,
      customer: {
        id: 8567196057890,
        email: "lakshya@giftkart.ai",
        created_at: "2024-12-23T02:44:23-05:00",
        updated_at: "2025-01-16T06:25:11-05:00",
        first_name: null,
        last_name: "",
        state: "disabled",
        note: null,
        verified_email: true,
        multipass_identifier: null,
        tax_exempt: false,
        phone: null,
        email_marketing_consent: {
          state: "not_subscribed",
          opt_in_level: "single_opt_in",
          consent_updated_at: null,
        },
        sms_marketing_consent: null,
        tags: "",
        currency: "INR",
        tax_exemptions: [],
        admin_graphql_api_id: "gid://shopify/Customer/8567196057890",
        default_address: {
          id: 11894915072290,
          customer_id: 8567196057890,
          first_name: null,
          last_name: "",
          company: null,
          address1: "Sector D Vasant Kunj",
          address2: null,
          city: "New Delhi",
          province: "Delhi",
          country: "India",
          zip: "110070",
          phone: null,
          name: "",
          province_code: "DL",
          country_code: "IN",
          country_name: "India",
          default: true,
        },
      },
      discount_applications: [],
      fulfillments: [
        {
          id: 5404046623010,
          admin_graphql_api_id: "gid://shopify/Fulfillment/5404046623010",
          created_at: "2025-01-16T06:26:46-05:00",
          location_id: 104064745762,
          name: "#1054.1",
          order_id: 6108091121954,
          origin_address: {},
          receipt: {},
          service: "manual",
          shipment_status: null,
          status: "success",
          tracking_company: "AGS",
          tracking_number: "1234567",
          tracking_numbers: ["1234567"],
          tracking_url: "https://tracking.agsystems.com/",
          tracking_urls: ["https://tracking.agsystems.com/"],
          updated_at: "2025-01-16T06:26:46-05:00",
          line_items: [
            {
              id: 15200232046882,
              admin_graphql_api_id: "gid://shopify/LineItem/15200232046882",
              attributed_staffs: [],
              current_quantity: 1,
              fulfillable_quantity: 0,
              fulfillment_service: "manual",
              fulfillment_status: "fulfilled",
              gift_card: false,
              grams: 0,
              name: "Pearl Blossom Set 1 - With Packaging",
              price: "2100.00",
              price_set: {
                shop_money: {
                  amount: "2100.00",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "2100.00",
                  currency_code: "INR",
                },
              },
              product_exists: true,
              product_id: 9609965699362,
              properties: [],
              quantity: 1,
              requires_shipping: true,
              sku: "12345678_P",
              taxable: true,
              title: "Pearl Blossom Set 1",
              total_discount: "0.00",
              total_discount_set: {
                shop_money: {
                  amount: "0.00",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "0.00",
                  currency_code: "INR",
                },
              },
              variant_id: 49548079399202,
              variant_inventory_management: "shopify",
              variant_title: "With Packaging",
              vendor: "giftclub-merchant-dev",
              tax_lines: [
                {
                  channel_liable: false,
                  price: "320.34",
                  price_set: {
                    shop_money: {
                      amount: "320.34",
                      currency_code: "INR",
                    },
                    presentment_money: {
                      amount: "320.34",
                      currency_code: "INR",
                    },
                  },
                  rate: 0.18,
                  title: "IGST",
                },
              ],
              duties: [],
              discount_allocations: [],
            },
          ],
        },
      ],
      line_items: [
        {
          id: 15200232046882,
          admin_graphql_api_id: "gid://shopify/LineItem/15200232046882",
          attributed_staffs: [],
          current_quantity: 1,
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 0,
          name: "Pearl Blossom Set 1 - With Packaging",
          price: "2100.00",
          price_set: {
            shop_money: {
              amount: "2100.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "2100.00",
              currency_code: "INR",
            },
          },
          product_exists: true,
          product_id: 9609965699362,
          properties: [],
          quantity: 1,
          requires_shipping: true,
          sku: "12345678_P",
          taxable: true,
          title: "Pearl Blossom Set 1",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: {
              amount: "0.00",
              currency_code: "INR",
            },
            presentment_money: {
              amount: "0.00",
              currency_code: "INR",
            },
          },
          variant_id: 49548079399202,
          variant_inventory_management: "shopify",
          variant_title: "With Packaging",
          vendor: "giftclub-merchant-dev",
          tax_lines: [
            {
              channel_liable: false,
              price: "320.34",
              price_set: {
                shop_money: {
                  amount: "320.34",
                  currency_code: "INR",
                },
                presentment_money: {
                  amount: "320.34",
                  currency_code: "INR",
                },
              },
              rate: 0.18,
              title: "IGST",
            },
          ],
          duties: [],
          discount_allocations: [],
        },
      ],
      payment_terms: null,
      refunds: [],
      shipping_address: {
        first_name: null,
        address1: "Sector D Vasant Kunj",
        phone: null,
        city: "New Delhi",
        zip: "110070",
        province: "Delhi",
        country: "India",
        last_name: "",
        address2: null,
        company: null,
        latitude: 28.5254842,
        longitude: 77.1433249,
        name: "",
        country_code: "IN",
        province_code: "DL",
      },
      shipping_lines: [],
      returns: [],
    },
    metadata: {
      "Content-Type": "application/json",
      "X-Shopify-Topic": "orders/fulfilled",
      "X-Shopify-Shop-Domain": "giftkart-merchant-dev.myshopify.com",
      "X-Shopify-Order-Id": "6108091121954",
      "X-Shopify-Test": "false",
      "X-Shopify-Hmac-SHA256": "FuMK+x1JRMBnsYCOpMXGaAhK8TaYi+PUL+BL58t+2Us=",
      "X-Shopify-Webhook-Id": "1aeafd9b-5c7c-4a19-aaf0-d65c477ec601",
      "X-Shopify-API-Version": "2024-10",
      "X-Shopify-Event-Id": "10a993a8-2718-4bc6-bbda-166c18027b2d",
      "X-Shopify-Triggered-At": "2025-01-16T11:26:47.135951865Z",
    },
  },
};

export const CREATE_PRODUCT = {
  version: "0",
  id: "5d3aa06d-4178-0a99-6907-4160ac555293",
  "detail-type": "shopifyWebhook",
  source:
    "aws.partner/shopify.com/202204020737/Giftclub_dev-Giftclub_Merchant_Dev",
  account: "442426894654",
  time: "2025-01-23T08:10:49Z",
  region: "ap-south-1",
  resources: [],
  detail: {
    payload: {
      admin_graphql_api_id: "gid://shopify/Product/9616657023266",
      body_html: "<p>xyz</p>",
      created_at: "2025-01-23T03:10:46-05:00",
      handle: "test-product",
      id: 9616657023266,
      product_type: "",
      published_at: "2025-01-23T03:10:46-05:00",
      template_suffix: "",
      title: "test product",
      updated_at: "2025-01-23T03:10:48-05:00",
      vendor: "giftclub-merchant-dev",
      status: "active",
      published_scope: "global",
      tags: "",
      variants: [
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571497345314",
          barcode: "",
          compare_at_price: "200.00",
          created_at: "2025-01-23T03:10:47-05:00",
          id: 49571497345314,
          inventory_policy: "deny",
          position: 2,
          price: "3000.00",
          product_id: 9616657023266,
          sku: "",
          taxable: true,
          title: "Red",
          updated_at: "2025-01-23T03:10:47-05:00",
          option1: "Red",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597438419234,
          inventory_quantity: 0,
          old_inventory_quantity: 0,
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571497378082",
          barcode: "",
          compare_at_price: "200.00",
          created_at: "2025-01-23T03:10:47-05:00",
          id: 49571497378082,
          inventory_policy: "deny",
          position: 3,
          price: "3000.00",
          product_id: 9616657023266,
          sku: "",
          taxable: true,
          title: "Bronze",
          updated_at: "2025-01-23T03:10:47-05:00",
          option1: "Bronze",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597438452002,
          inventory_quantity: 0,
          old_inventory_quantity: 0,
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571497410850",
          barcode: "",
          compare_at_price: "200.00",
          created_at: "2025-01-23T03:10:47-05:00",
          id: 49571497410850,
          inventory_policy: "deny",
          position: 4,
          price: "3000.00",
          product_id: 9616657023266,
          sku: "",
          taxable: true,
          title: "Brown",
          updated_at: "2025-01-23T03:10:47-05:00",
          option1: "Brown",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597438484770,
          inventory_quantity: 0,
          old_inventory_quantity: 0,
        },
      ],
      options: [
        {
          name: "Color",
          id: 12072077000994,
          product_id: 9616657023266,
          position: 1,
          values: ["Red", "Bronze", "Brown"],
        },
      ],
      images: [],
      image: null,
      media: [],
      variant_gids: [
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571497345314",
          updated_at: "2025-01-23T08:10:47.000Z",
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571497378082",
          updated_at: "2025-01-23T08:10:47.000Z",
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571497410850",
          updated_at: "2025-01-23T08:10:47.000Z",
        },
      ],
      has_variants_that_requires_components: false,
      category: {
        admin_graphql_api_id: "gid://shopify/TaxonomyCategory/aa-2-14-6",
        name: "Hair Pins, Claws & Clips",
        full_name:
          "Apparel & Accessories > Clothing Accessories > Hair Accessories > Hair Pins, Claws & Clips",
      },
    },
    metadata: {
      "Content-Type": "application/json",
      "X-Shopify-Topic": "products/create",
      "X-Shopify-Shop-Domain": "giftkart-merchant-dev.myshopify.com",
      "X-Shopify-Product-Id": "9616657023266",
      "X-Shopify-Hmac-SHA256": "wBy5qHwvxvR+nKNDIrYdpaWVb55lHzIcNPsDGaabOas=",
      "X-Shopify-Webhook-Id": "d03ffe12-e2b6-4a97-aacf-5fde6cfbb9f5",
      "X-Shopify-API-Version": "2024-10",
      "X-Shopify-Event-Id": "598ac5b6-7582-4cfa-bea2-301fcf39df55",
      "X-Shopify-Triggered-At": "2025-01-23T08:10:47.076293528Z",
    },
  },
};

export const PRODUCT_UPDATE = {
  version: "0",
  id: "dbab180e-2bee-2e7a-2a47-d7534f1d27e9",
  "detail-type": "shopifyWebhook",
  source:
    "aws.partner/shopify.com/202204020737/Giftclub_dev-Giftclub_Merchant_Dev",
  account: "442426894654",
  time: "2025-01-23T08:45:24Z",
  region: "ap-south-1",
  resources: [],
  detail: {
    payload: {
      admin_graphql_api_id: "gid://shopify/Product/9616711090466",
      body_html:
        "<p>The upper is set on a striped cotton base, featuring a moody colour palette. The same hues of terracotta, maroon, blue and eggshell are used to create a checkered pattern with threadwork embroidery to add some texture. The upper is further highlighted with iridescent sequins. The back has a plain maroon silk base, with gold twine and sequin lace helping accentuate the design.</p>",
      created_at: "2025-01-23T03:45:21-05:00",
      handle: "magnum",
      id: 9616711090466,
      product_type: "",
      published_at: "2025-01-23T03:45:21-05:00",
      template_suffix: "",
      title: "Magnum",
      updated_at: "2025-01-23T03:45:23-05:00",
      vendor: "giftclub-merchant-dev",
      status: "active",
      published_scope: "global",
      tags: "",
      variants: [
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630350626",
          barcode: "",
          compare_at_price: "2699.00",
          created_at: "2025-01-23T03:45:22-05:00",
          id: 49571630350626,
          inventory_policy: "deny",
          position: 2,
          price: "1899.00",
          product_id: 9616711090466,
          sku: "",
          taxable: true,
          title: "Black",
          updated_at: "2025-01-23T03:45:22-05:00",
          option1: "Black",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597571424546,
          inventory_quantity: 30,
          old_inventory_quantity: 30,
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630383394",
          barcode: "",
          compare_at_price: "2699.00",
          created_at: "2025-01-23T03:45:22-05:00",
          id: 49571630383394,
          inventory_policy: "deny",
          position: 3,
          price: "1899.00",
          product_id: 9616711090466,
          sku: "",
          taxable: true,
          title: "Blue",
          updated_at: "2025-01-23T03:45:22-05:00",
          option1: "Blue",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597571457314,
          inventory_quantity: 20,
          old_inventory_quantity: 20,
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630416162",
          barcode: "",
          compare_at_price: "2699.00",
          created_at: "2025-01-23T03:45:22-05:00",
          id: 49571630416162,
          inventory_policy: "deny",
          position: 4,
          price: "1899.00",
          product_id: 9616711090466,
          sku: "",
          taxable: true,
          title: "Red",
          updated_at: "2025-01-23T03:45:22-05:00",
          option1: "Red",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597571490082,
          inventory_quantity: 10,
          old_inventory_quantity: 10,
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630448930",
          barcode: "",
          compare_at_price: "2699.00",
          created_at: "2025-01-23T03:45:22-05:00",
          id: 49571630448930,
          inventory_policy: "deny",
          position: 5,
          price: "1899.00",
          product_id: 9616711090466,
          sku: "",
          taxable: true,
          title: "Pink",
          updated_at: "2025-01-23T03:45:22-05:00",
          option1: "Pink",
          option2: null,
          option3: null,
          image_id: null,
          inventory_item_id: 51597571522850,
          inventory_quantity: 10,
          old_inventory_quantity: 10,
        },
      ],
      options: [
        {
          name: "Color",
          id: 12072158560546,
          product_id: 9616711090466,
          position: 1,
          values: ["Black", "Blue", "Red", "Pink"],
        },
      ],
      images: [
        {
          id: 59020646973730,
          product_id: 9616711090466,
          position: 1,
          created_at: "2025-01-23T03:44:07-05:00",
          updated_at: "2025-01-23T03:45:21-05:00",
          alt: null,
          width: 1000,
          height: 1000,
          src: "https://cdn.shopify.com/s/files/1/0921/3732/4834/files/magnum-563468.jpg?v=1737621848",
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/ProductImage/59020646973730",
        },
      ],
      image: {
        id: 59020646973730,
        product_id: 9616711090466,
        position: 1,
        created_at: "2025-01-23T03:44:07-05:00",
        updated_at: "2025-01-23T03:45:21-05:00",
        alt: null,
        width: 1000,
        height: 1000,
        src: "https://cdn.shopify.com/s/files/1/0921/3732/4834/files/magnum-563468.jpg?v=1737621848",
        variant_ids: [],
        admin_graphql_api_id: "gid://shopify/ProductImage/59020646973730",
      },
      media: [
        {
          id: 50951981826338,
          product_id: 9616711090466,
          position: 1,
          created_at: "2025-01-23T03:44:07-05:00",
          updated_at: "2025-01-23T03:45:21-05:00",
          alt: null,
          status: "READY",
          media_content_type: "IMAGE",
          preview_image: {
            width: 1000,
            height: 1000,
            src: "https://cdn.shopify.com/s/files/1/0921/3732/4834/files/magnum-563468.jpg?v=1737621848",
            status: "READY",
          },
          variant_ids: [],
          admin_graphql_api_id: "gid://shopify/MediaImage/50951981826338",
        },
      ],
      variant_gids: [
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630350626",
          updated_at: "2025-01-23T08:45:22.000Z",
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630383394",
          updated_at: "2025-01-23T08:45:22.000Z",
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630416162",
          updated_at: "2025-01-23T08:45:22.000Z",
        },
        {
          admin_graphql_api_id: "gid://shopify/ProductVariant/49571630448930",
          updated_at: "2025-01-23T08:45:22.000Z",
        },
      ],
      has_variants_that_requires_components: false,
      category: {
        admin_graphql_api_id: "gid://shopify/TaxonomyCategory/aa-8-9",
        name: "Flats",
        full_name: "Apparel & Accessories > Shoes > Flats",
      },
    },
    metadata: {
      "Content-Type": "application/json",
      "X-Shopify-Topic": "products/update",
      "X-Shopify-Shop-Domain": "giftkart-merchant-dev.myshopify.com",
      "X-Shopify-Product-Id": "9616711090466",
      "X-Shopify-Hmac-SHA256": "sJIkhKT38a/OVm2jMlQq5JXy/2aZlAfnwpa3ZVIz5do=",
      "X-Shopify-Webhook-Id": "90452f36-1775-42c3-b580-ad75cb3fdc05",
      "X-Shopify-API-Version": "2024-10",
      "X-Shopify-Event-Id": "8f5ea559-3f19-4c96-8977-74fc07ed6fee",
      "X-Shopify-Triggered-At": "2025-01-23T08:45:23.163369928Z",
    },
  },
};

export const APP_UNINSTALL = {
  version: "0",
  id: "7f54051a-8835-d03d-a89a-6f00e73d89fc",
  "detail-type": "shopifyWebhook",
  source:
    "aws.partner/shopify.com/202204020737/Giftclub_dev-Giftclub_Merchant_Dev",
  account: "442426894654",
  time: "2025-01-31T07:25:27Z",
  region: "ap-south-1",
  resources: [],
  detail: {
    payload: {
      id: 92137324834,
      name: "giftclub-merchant-dev",
      email: "lakshya@giftkart.ai",
      domain: "giftkart-merchant-dev.myshopify.com",
      province: null,
      country: "IN",
      address1: null,
      zip: null,
      city: null,
      source: null,
      phone: null,
      latitude: null,
      longitude: null,
      primary_locale: "en",
      address2: null,
      created_at: "2024-12-23T01:56:03-05:00",
      updated_at: "2025-01-27T22:06:23-05:00",
      country_code: "IN",
      country_name: "India",
      currency: "INR",
      customer_email: "lakshya@giftkart.ai",
      timezone: "(GMT-05:00) America/New_York",
      iana_timezone: "America/New_York",
      shop_owner: "Lakshya Tiwari",
      money_format: "Rs. {{amount}}",
      money_with_currency_format: "Rs. {{amount}}",
      weight_unit: "kg",
      province_code: null,
      taxes_included: true,
      auto_configure_tax_inclusivity: false,
      tax_shipping: false,
      county_taxes: true,
      plan_display_name: "Development",
      plan_name: "affiliate",
      has_discounts: false,
      has_gift_cards: false,
      myshopify_domain: "giftkart-merchant-dev.myshopify.com",
      google_apps_domain: null,
      google_apps_login_enabled: null,
      money_in_emails_format: "Rs. {{amount}}",
      money_with_currency_in_emails_format: "Rs. {{amount}}",
      eligible_for_payments: false,
      requires_extra_payments_agreement: false,
      password_enabled: true,
      has_storefront: true,
      finances: true,
      primary_location_id: 104064745762,
      checkout_api_supported: false,
      multi_location_enabled: true,
      setup_required: false,
      pre_launch_enabled: false,
      enabled_presentment_currencies: ["INR"],
      marketing_sms_consent_enabled_at_checkout: false,
      transactional_sms_disabled: true,
    },
    metadata: {
      "Content-Type": "application/json",
      "X-Shopify-Topic": "app/uninstalled",
      "X-Shopify-Shop-Domain": "giftkart-merchant-dev.myshopify.com",
      "X-Shopify-Hmac-SHA256": "eMDSYdcSowTX+DEe3Mqs5AIiJH9QGVmdXcc/htJ8Obg=",
      "X-Shopify-Webhook-Id": "6b60eaf8-e30f-4e19-b4da-7c6927ce72c5",
      "X-Shopify-API-Version": "2024-10",
      "X-Shopify-Event-Id": "7e05ae51-d39d-4350-a55c-bed3b4a67f24",
      "X-Shopify-Triggered-At": "2025-01-31T07:25:25.539972216Z",
    },
  },
};
